import { useEffect, useMemo, useState } from 'react'
import { Braces, CaseSensitive, Code2, FileJson, FileSpreadsheet, GitBranch, Image, Link, Maximize2, Menu, Minimize2, RotateCcw, ShieldCheck, Sparkles, X } from 'lucide-react'
import { AppLayout, ErrorMessage, OutputPanel, TextAreaPanel } from './components/Panels'
import { ConverterCard, type ConverterItem } from './components/ConverterCard'
import { FileDropzone } from './components/FileDropzone'
import { DownloadButton, ThemeToggle } from './components/Buttons'
import { base64Convert, convertCase, csvToJson, formatJson, formatXml, jsonToCsv, markdownToHtml, urlConvert, type ConversionResult, type TextCase } from './utils/textConverters'
import { processImage } from './utils/imageConverters'

const converters: ConverterItem[] = [
  {id:'csv-json',name:'CSV to JSON',description:'Turn spreadsheet data into JSON',icon:FileSpreadsheet,accent:'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-400'},
  {id:'json-csv',name:'JSON to CSV',description:'Export JSON objects as CSV',icon:FileJson,accent:'bg-sky-100 text-sky-700 dark:bg-sky-950 dark:text-sky-400'},
  {id:'json-format',name:'JSON Formatter',description:'Beautify or minify JSON',icon:Braces,accent:'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-400'},
  {id:'markdown',name:'Markdown to HTML',description:'Render Markdown into HTML',icon:Code2,accent:'bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-400'},
  {id:'case',name:'Text Case',description:'Change text casing instantly',icon:CaseSensitive,accent:'bg-pink-100 text-pink-700 dark:bg-pink-950 dark:text-pink-400'},
  {id:'image',name:'Image Converter',description:'Convert JPG, PNG, and WebP',icon:Image,accent:'bg-cyan-100 text-cyan-700 dark:bg-cyan-950 dark:text-cyan-400'},
  {id:'resize',name:'Image Resizer',description:'Resize images by pixels',icon:Maximize2,accent:'bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-400'},
  {id:'base64',name:'Base64',description:'Encode or decode text',icon:Minimize2,accent:'bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-400'},
  {id:'url',name:'URL Encoder',description:'Encode or decode URL text',icon:Link,accent:'bg-teal-100 text-teal-700 dark:bg-teal-950 dark:text-teal-400'},
  {id:'xml',name:'XML Formatter',description:'Validate and beautify XML',icon:Code2,accent:'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-400'},
]
const samples:Record<string,string>={
  'csv-json':'name,email,role\nAda Lovelace,ada@example.com,Engineer\nGrace Hopper,grace@example.com,Admiral',
  'json-csv':'[\n  {"name":"Ada","language":"Analytical Engine"},\n  {"name":"Grace","language":"COBOL"}\n]',
  'json-format':'{"project":"Universal File Converter","private":true,"formats":["CSV","JSON","XML"]}',
  markdown:'# Hello, world!\n\nThis is **private**, browser-based conversion.\n\n- Fast\n- Secure\n- Free',
  case:'the quick brown fox jumps over the lazy dog', base64:'Convert me safely 🔒', url:'https://example.com/search?q=hello world&sort=newest',
  xml:'<catalog><book id="1"><title>Clean Code</title><author>Robert Martin</author></book></catalog>'
}

function Header({dark,toggle}:{dark:boolean;toggle:()=>void}) { const [open,setOpen]=useState(false); return <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur dark:border-slate-800 dark:bg-slate-950/90"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand-600 text-white"><Sparkles size={19}/></span><div><strong className="block text-sm text-slate-950 dark:text-white sm:text-base">Universal File Converter</strong><span className="hidden text-[11px] text-slate-500 sm:block">Simple. Private. In your browser.</span></div></div><div className="flex items-center gap-2"><a className="hidden items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium hover:bg-slate-100 dark:hover:bg-slate-800 sm:flex" href="https://github.com/your-username/universal-file-converter" target="_blank" rel="noreferrer"><GitBranch size={18}/> GitHub</a><ThemeToggle dark={dark} onToggle={toggle}/><button className="icon-btn sm:hidden" onClick={()=>setOpen(!open)}>{open?<X size={19}/>:<Menu size={19}/>}</button></div></div>{open&&<a className="flex items-center gap-2 border-t p-4 text-sm dark:border-slate-800" href="https://github.com/your-username/universal-file-converter"><GitBranch size={18}/> View on GitHub</a>}</header> }

export default function App(){
 const [dark,setDark]=useState(()=>localStorage.theme==='dark'||(!('theme' in localStorage)&&matchMedia('(prefers-color-scheme: dark)').matches)); const [selected,setSelected]=useState('csv-json'); const [input,setInput]=useState(''); const [output,setOutput]=useState<ConversionResult>({output:'',mime:'text/plain',extension:'txt'}); const [error,setError]=useState(''); const [mode,setMode]=useState('format'); const [file,setFile]=useState<File|null>(null); const [imageResult,setImageResult]=useState<{url:string;blob:Blob}|null>(null); const [format,setFormat]=useState<'image/jpeg'|'image/png'|'image/webp'>('image/webp'); const [width,setWidth]=useState(''); const [height,setHeight]=useState(''); const [busy,setBusy]=useState(false)
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.theme=dark?'dark':'light'},[dark]); const item=useMemo(()=>converters.find(c=>c.id===selected)!,[selected]);
 const reset=()=>{setInput('');setOutput({output:'',mime:'text/plain',extension:'txt'});setError('');setFile(null);if(imageResult)URL.revokeObjectURL(imageResult.url);setImageResult(null);setWidth('');setHeight('')};
 const select=(id:string)=>{setSelected(id);reset();setMode(id==='json-format'?'format':id==='case'?'title':'encode')};
 const readFile=async(f:File)=>{setFile(f);setError('');if(!['image','resize'].includes(selected)){try{setInput(await f.text())}catch{setError('Unable to read this file.')}}};
 const convert=async()=>{setError('');setBusy(true);try{let r:ConversionResult;if(selected==='csv-json')r=csvToJson(input);else if(selected==='json-csv')r=jsonToCsv(input);else if(selected==='json-format')r=formatJson(input,mode==='minify');else if(selected==='markdown')r=await markdownToHtml(input);else if(selected==='case')r=convertCase(input,mode as TextCase);else if(selected==='base64')r=base64Convert(input,mode==='decode');else if(selected==='url')r=urlConvert(input,mode==='decode');else if(selected==='xml')r=formatXml(input);else{if(!file)throw new Error('Choose an image first.');const processed=await processImage(file,{format,width:selected==='resize'?Number(width)||undefined:undefined,height:selected==='resize'?Number(height)||undefined:undefined});if(imageResult)URL.revokeObjectURL(imageResult.url);setImageResult(processed);setBusy(false);return}setOutput(r)}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Please check your input.');setOutput({output:'',mime:'text/plain',extension:'txt'})}finally{setBusy(false)}};
 const imageTool=['image','resize'].includes(selected); const modes=selected==='json-format'?['format','minify']:selected==='case'?['upper','lower','title','sentence','camel','snake','kebab']:['encode','decode'];
 return <AppLayout header={<Header dark={dark} toggle={()=>setDark(!dark)}/>}><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><section className="mb-7"><h1 className="text-2xl font-extrabold tracking-tight text-slate-950 dark:text-white sm:text-3xl">What would you like to convert?</h1><p className="mt-2 max-w-2xl text-sm text-slate-500 sm:text-base">Pick a tool, add your content, and convert it in seconds—without anything leaving your device.</p></section><div className="no-scrollbar -mx-4 flex gap-3 overflow-x-auto px-4 pb-3 sm:mx-0 sm:grid sm:grid-cols-2 sm:px-0 lg:grid-cols-5">{converters.map(c=><ConverterCard key={c.id} item={c} active={c.id===selected} onClick={()=>select(c.id)}/>)}</div>
 <section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-7"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.accent}`}><item.icon size={21}/></span><div><h2 className="font-bold text-slate-950 dark:text-white">{item.name}</h2><p className="text-xs text-slate-500">{item.description}</p></div></div><button onClick={reset} className="btn-secondary"><RotateCcw size={16}/> Clear all</button></div><div className="space-y-5 p-5 sm:p-7">
 {imageTool?<><FileDropzone onFile={readFile} file={file} accept="image/jpeg,image/png,image/webp"/><div className="grid gap-4 sm:grid-cols-3"><label className="field"><span>Output format</span><select value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="image/webp">WebP</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option></select></label>{selected==='resize'&&<><label className="field"><span>Width (px)</span><input type="number" min="1" placeholder="Keep original" value={width} onChange={e=>setWidth(e.target.value)}/></label><label className="field"><span>Height (px)</span><input type="number" min="1" placeholder="Keep original" value={height} onChange={e=>setHeight(e.target.value)}/></label></>}</div>{imageResult&&<div className="rounded-2xl bg-slate-100 p-4 text-center dark:bg-slate-950"><img className="mx-auto max-h-80 rounded-lg object-contain" src={imageResult.url}/><div className="mt-4 flex justify-center"><DownloadButton blob={imageResult.blob} extension={format.split('/')[1].replace('jpeg','jpg')}/></div></div>}</>:<><div className="flex flex-wrap items-center justify-between gap-3"><FileDropzone onFile={readFile} file={file} accept=".txt,.csv,.json,.md,.xml,text/*"/><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>{setInput(samples[selected]||'');setError('')}}>Load sample</button>{['json-format','case','base64','url'].includes(selected)&&<div className="segmented">{modes.map(m=><button key={m} onClick={()=>setMode(m)} className={mode===m?'active':''}>{m}</button>)}</div>}</div></div><div className="grid gap-5 lg:grid-cols-2"><TextAreaPanel label="Input" value={input} onChange={setInput} placeholder={`Paste your ${item.name.toLowerCase()} input here…`}/><OutputPanel value={output.output} mime={output.mime} extension={output.extension}/></div></>}
 {error&&<ErrorMessage message={error}/>}<div className="flex justify-end"><button className="btn-primary px-6 py-3" disabled={busy||(!input&&!file)} onClick={convert}><Sparkles size={17}/>{busy?'Converting…':'Convert now'}</button></div></div><div className="flex items-center justify-center gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3 text-center text-xs font-medium text-slate-500 dark:border-slate-800 dark:bg-slate-950/50"><ShieldCheck size={16} className="text-emerald-500"/> Processed locally in your browser. Files are never uploaded.</div></section><footer className="py-8 text-center text-xs text-slate-400">Built for speed, privacy, and simplicity.</footer></div></AppLayout>
}
